### ISSUE TITLE
VsChromium does not show banner when new version is available

### ISSUE THREAD

**Issue by rpaquay** [chromium/vs-chromium#69]
This happens in VS 2015 and later. This is the result of making VsChromium an Async package, which happened in https://github.com/chromium/vs-chromium/commit/71221044d76a1a74238391cb6a4fd14153663058, which was released in [version 0.9.31](https://github.com/chromium/vs-chromium/releases/tag/v0.9.31)

Here is the error:

```
[2020-06-22 09:57:07.2679][VsChromium][31024-30][Error] Error checking for latest update information
[2020-06-22 09:57:07.2679][VsChromium][31024-30][Error]  Exception Type: System.InvalidOperationException
[2020-06-22 09:57:07.2679][VsChromium][31024-30][Error]  Exception Message: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.VsPackage.get_VsUIShell() in D:\src\projects\vs-chromium\src\VsChromium\VsPackage.cs:line 112
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.ToolWindows.ToolWindowAccessor.GetToolWindow[ToolWindow](Guid guid) in D:\src\projects\vs-chromium\src\VsChromium\Features\ToolWindows\ToolWindowAccessor.cs:line 24
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.ToolWindows.ToolWindowAccessor.get_CodeSearch() in D:\src\projects\vs-chromium\src\VsChromium\Features\ToolWindows\ToolWindowAccessor.cs:line 49
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.AutoUpdate.UpdateNotificationListener.NotifyUpdate(UpdateInfo updateInfo) in D:\src\projects\vs-chromium\src\VsChromium\Features\AutoUpdate\UpdateNotificationListener.cs:line 15
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.AutoUpdate.UpdateChecker.<>c__DisplayClass13_0.<NotifyUpdate>b__0(IUpdateNotificationListener x) in D:\src\projects\vs-chromium\src\VsChromium\Features\AutoUpdate\UpdateChecker.cs:line 77
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Core.Linq.EnumerableExtensions.ForAll[TSource](IEnumerable`1 source, Action`1 action) in D:\src\projects\vs-chromium\src\Core\Linq\EnumerableExtensions.cs:line 175
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.AutoUpdate.UpdateChecker.NotifyUpdate(UpdateInfo updateInfo) in D:\src\projects\vs-chromium\src\VsChromium\Features\AutoUpdate\UpdateChecker.cs:line 77
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.AutoUpdate.UpdateChecker.PerformVersionCheck() in D:\src\projects\vs-chromium\src\VsChromium\Features\AutoUpdate\UpdateChecker.cs:line 71
[2020-06-22 09:57:07.2928][VsChromium][31024-30][Error]  +    at VsChromium.Features.AutoUpdate.UpdateChecker.RunCheck() in D:\src\projects\vs-chromium\src\VsChromium\Features\AutoUpdate\UpdateChecker.cs:line 59

```

**Comment by rpaquay** [comment]
This is fixed in [version 0.9.36](https://github.com/chromium/vs-chromium/releases/tag/v0.9.36)
